name: Test Github Action
run-name: run name
on:
  repository_dispatch:
    types: hey
jobs:
  configute_:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: plan
        run: |-
          ./main.sh
