name: Test Github Action
run-name: run name
on:
  workflow_dispatch:
jobs:
  configute_:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: plan  
        run: |-
          ./main.sh
